sudo: false
env: RSPEC_RETRY=true
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.0
  - 2.3.6
  - 2.4.1
  - 2.6.7
  - 2.7.3
  - 3.0.0
before_install:
  - git submodule update --init --recursive
script: bundle exec rspec
notifications:
  slack:
    secure: wIcB0kscOcVO41zOkOBLHDphzq/Lowrn40MI2mqQtcWcFkvHzcn3fIPoEH0YR8eul7bZ6ZHOLlJw3Qs8gE6VfrqLFVzZuAAv2vtzh26xkZCuQwmCn0o576mTWMSB6H8q71+t7GHZUL/ctMKtJNzwRBilppSaLjktEynS7UdiVO8=
