# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'webmock/rspec'

require 'ably-rest'

$:.push File.expand_path('../lib/submodules/ably-ruby/spec', File.dirname(__FILE__))

require 'support/api_helper'
require 'support/event_machine_helper'

require 'rspec_config'

def require_tests_from(path)
  Dir.glob(File.expand_path("../lib/submodules/ably-ruby/spec/#{path}/*.rb", File.dirname(__FILE__))).each do |file|
    require file
  end
end
