# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'webmock/rspec'

require 'ably-rest'

$:.push File.expand_path('../lib/submodules/ably-ruby/spec', File.dirname(__FILE__))

require 'support/api_helper'
require 'support/private_api_formatter'
require 'support/protocol_helper'
require 'support/random_helper'

require 'rspec_config'

def require_tests_from(path, options = {})
  ignore_files = options.fetch(:ignore_file_macher, nil)
  Dir.glob(File.expand_path("../lib/submodules/ably-ruby/spec/#{path}/*.rb", File.dirname(__FILE__))).each do |file|
    require file if ignore_files.nil? || !File.basename(file).match(ignore_files)
  end
end
